from . import product
from . import nettix_info
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import trade_in
from . import boat_model
from . import res_users
from . import account_invoice